/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package org.dataone.daks.provexdb.DAO.models.dto;

import com.spoledge.audao.db.dto.AbstractDto;

/**
 * This is a DTO class.
 *
 * @author generated
 */
public class Edge extends AbstractDto {

    ////////////////////////////////////////////////////////////////////////////
    // Static
    ////////////////////////////////////////////////////////////////////////////

    public static final String TABLE = "edge";

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////

    private String traceId;
    private String startNodeId;
    private String endNodeId;
    private String edgeLabel;
    private String edgeType;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public Edge() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public String getTraceId() {
        return traceId;
    }

    public void setTraceId( String _val) {
        this.traceId = _val;
    }

    public String getStartNodeId() {
        return startNodeId;
    }

    public void setStartNodeId( String _val) {
        this.startNodeId = _val;
    }

    public String getEndNodeId() {
        return endNodeId;
    }

    public void setEndNodeId( String _val) {
        this.endNodeId = _val;
    }

    public String getEdgeLabel() {
        return edgeLabel;
    }

    public void setEdgeLabel( String _val) {
        this.edgeLabel = _val;
    }

    public String getEdgeType() {
        return edgeType;
    }

    public void setEdgeType( String _val) {
        this.edgeType = _val;
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     * Uses 'columns' equality type.
     */
    @Override
    public boolean equals( Object _other ) {
        if (_other == this) return true;
        if (_other == null || (!(_other instanceof Edge))) return false;

        Edge _o = (Edge) _other;

        if ( traceId == null ) {
            if ( _o.traceId != null ) return false;
        }
        else if ( _o.traceId == null || !traceId.equals( _o.traceId )) return false;

        if ( startNodeId == null ) {
            if ( _o.startNodeId != null ) return false;
        }
        else if ( _o.startNodeId == null || !startNodeId.equals( _o.startNodeId )) return false;

        if ( endNodeId == null ) {
            if ( _o.endNodeId != null ) return false;
        }
        else if ( _o.endNodeId == null || !endNodeId.equals( _o.endNodeId )) return false;

        if ( edgeLabel == null ) {
            if ( _o.edgeLabel != null ) return false;
        }
        else if ( _o.edgeLabel == null || !edgeLabel.equals( _o.edgeLabel )) return false;

        if ( edgeType == null ) {
            if ( _o.edgeType != null ) return false;
        }
        else if ( _o.edgeType == null || !edgeType.equals( _o.edgeType )) return false;

        return true;
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        int _ret = 2154973; // = "Edge".hashCode()
        _ret += traceId == null ? 0 : traceId.hashCode();
        _ret = 29 * _ret + (startNodeId == null ? 0 : startNodeId.hashCode());
        _ret = 29 * _ret + (endNodeId == null ? 0 : endNodeId.hashCode());
        _ret = 29 * _ret + (edgeLabel == null ? 0 : edgeLabel.hashCode());
        _ret = 29 * _ret + (edgeType == null ? 0 : edgeType.hashCode());

        return _ret;
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "traceId", traceId );
        append( sb, "startNodeId", startNodeId );
        append( sb, "endNodeId", endNodeId );
        append( sb, "edgeLabel", edgeLabel );
        append( sb, "edgeType", edgeType );
    }
}
