/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package org.dataone.daks.provexdb.DAO.models.dto;

import com.spoledge.audao.db.dto.AbstractDto;

/**
 * This is a DTO class.
 *
 * @author generated
 */
public class TcTemp extends AbstractDto {

    ////////////////////////////////////////////////////////////////////////////
    // Static
    ////////////////////////////////////////////////////////////////////////////

    public static final String TABLE = "tc_temp";

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////

    private String startNodeId;
    private String endNodeId;
    private Integer inRound;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public TcTemp() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public String getStartNodeId() {
        return startNodeId;
    }

    public void setStartNodeId( String _val) {
        this.startNodeId = _val;
    }

    public String getEndNodeId() {
        return endNodeId;
    }

    public void setEndNodeId( String _val) {
        this.endNodeId = _val;
    }

    public Integer getInRound() {
        return inRound;
    }

    public void setInRound( Integer _val) {
        this.inRound = _val;
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     * Uses 'columns' equality type.
     */
    @Override
    public boolean equals( Object _other ) {
        if (_other == this) return true;
        if (_other == null || (!(_other instanceof TcTemp))) return false;

        TcTemp _o = (TcTemp) _other;

        if ( startNodeId == null ) {
            if ( _o.startNodeId != null ) return false;
        }
        else if ( _o.startNodeId == null || !startNodeId.equals( _o.startNodeId )) return false;

        if ( endNodeId == null ) {
            if ( _o.endNodeId != null ) return false;
        }
        else if ( _o.endNodeId == null || !endNodeId.equals( _o.endNodeId )) return false;

        if ( inRound == null ) {
            if ( _o.inRound != null ) return false;
        }
        else if ( _o.inRound == null || inRound.intValue() != _o.inRound.intValue()) return false;

        return true;
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        int _ret = -1796087037; // = "TcTemp".hashCode()
        _ret += startNodeId == null ? 0 : startNodeId.hashCode();
        _ret = 29 * _ret + (endNodeId == null ? 0 : endNodeId.hashCode());
        _ret = 29 * _ret + (inRound == null ? 0 : inRound);

        return _ret;
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "startNodeId", startNodeId );
        append( sb, "endNodeId", endNodeId );
        append( sb, "inRound", inRound );
    }
}
