/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package org.dataone.daks.provexdb.DAO.models.dto;

import com.spoledge.audao.db.dto.AbstractDto;

/**
 * This is a DTO class.
 *
 * @author generated
 */
public class UserRequestMaster extends AbstractDto {

    ////////////////////////////////////////////////////////////////////////////
    // Static
    ////////////////////////////////////////////////////////////////////////////

    public static final String TABLE = "user_request_master";

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////

    private String traceId;
    private String reqId;
    private String evalType;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public UserRequestMaster() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public String getTraceId() {
        return traceId;
    }

    public void setTraceId( String _val) {
        this.traceId = _val;
    }

    public String getReqId() {
        return reqId;
    }

    public void setReqId( String _val) {
        this.reqId = _val;
    }

    public String getEvalType() {
        return evalType;
    }

    public void setEvalType( String _val) {
        this.evalType = _val;
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     * Uses 'columns' equality type.
     */
    @Override
    public boolean equals( Object _other ) {
        if (_other == this) return true;
        if (_other == null || (!(_other instanceof UserRequestMaster))) return false;

        UserRequestMaster _o = (UserRequestMaster) _other;

        if ( traceId == null ) {
            if ( _o.traceId != null ) return false;
        }
        else if ( _o.traceId == null || !traceId.equals( _o.traceId )) return false;

        if ( reqId == null ) {
            if ( _o.reqId != null ) return false;
        }
        else if ( _o.reqId == null || !reqId.equals( _o.reqId )) return false;

        if ( evalType == null ) {
            if ( _o.evalType != null ) return false;
        }
        else if ( _o.evalType == null || !evalType.equals( _o.evalType )) return false;

        return true;
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        int _ret = -1656756314; // = "UserRequestMaster".hashCode()
        _ret += traceId == null ? 0 : traceId.hashCode();
        _ret = 29 * _ret + (reqId == null ? 0 : reqId.hashCode());
        _ret = 29 * _ret + (evalType == null ? 0 : evalType.hashCode());

        return _ret;
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "traceId", traceId );
        append( sb, "reqId", reqId );
        append( sb, "evalType", evalType );
    }
}
