/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package org.dataone.daks.provexdb.DAO.models.dto;

import com.spoledge.audao.db.dto.AbstractDto;

/**
 * This is a DTO class.
 *
 * @author generated
 */
public class UserRequestDetail extends AbstractDto {

    ////////////////////////////////////////////////////////////////////////////
    // Static
    ////////////////////////////////////////////////////////////////////////////

    public static final String TABLE = "user_request_detail";

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////

    private String reqId;
    private String stageId;
    private String reqType;
    private String nodeId;
    private String targetNodeId;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public UserRequestDetail() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public String getReqId() {
        return reqId;
    }

    public void setReqId( String _val) {
        this.reqId = _val;
    }

    public String getStageId() {
        return stageId;
    }

    public void setStageId( String _val) {
        this.stageId = _val;
    }

    public String getReqType() {
        return reqType;
    }

    public void setReqType( String _val) {
        this.reqType = _val;
    }

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId( String _val) {
        this.nodeId = _val;
    }

    public String getTargetNodeId() {
        return targetNodeId;
    }

    public void setTargetNodeId( String _val) {
        this.targetNodeId = _val;
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     * Uses 'columns' equality type.
     */
    @Override
    public boolean equals( Object _other ) {
        if (_other == this) return true;
        if (_other == null || (!(_other instanceof UserRequestDetail))) return false;

        UserRequestDetail _o = (UserRequestDetail) _other;

        if ( reqId == null ) {
            if ( _o.reqId != null ) return false;
        }
        else if ( _o.reqId == null || !reqId.equals( _o.reqId )) return false;

        if ( stageId == null ) {
            if ( _o.stageId != null ) return false;
        }
        else if ( _o.stageId == null || !stageId.equals( _o.stageId )) return false;

        if ( reqType == null ) {
            if ( _o.reqType != null ) return false;
        }
        else if ( _o.reqType == null || !reqType.equals( _o.reqType )) return false;

        if ( nodeId == null ) {
            if ( _o.nodeId != null ) return false;
        }
        else if ( _o.nodeId == null || !nodeId.equals( _o.nodeId )) return false;

        if ( targetNodeId == null ) {
            if ( _o.targetNodeId != null ) return false;
        }
        else if ( _o.targetNodeId == null || !targetNodeId.equals( _o.targetNodeId )) return false;

        return true;
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        int _ret = -1910712939; // = "UserRequestDetail".hashCode()
        _ret += reqId == null ? 0 : reqId.hashCode();
        _ret = 29 * _ret + (stageId == null ? 0 : stageId.hashCode());
        _ret = 29 * _ret + (reqType == null ? 0 : reqType.hashCode());
        _ret = 29 * _ret + (nodeId == null ? 0 : nodeId.hashCode());
        _ret = 29 * _ret + (targetNodeId == null ? 0 : targetNodeId.hashCode());

        return _ret;
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "reqId", reqId );
        append( sb, "stageId", stageId );
        append( sb, "reqType", reqType );
        append( sb, "nodeId", nodeId );
        append( sb, "targetNodeId", targetNodeId );
    }
}
