/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package org.dataone.daks.provexdb.DAO.models.dao.mysql;


import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.sql.Types;

import java.util.ArrayList;

import com.spoledge.audao.db.dao.AbstractDaoImpl;
import com.spoledge.audao.db.dao.DBException;
import com.spoledge.audao.db.dao.DaoException;


import org.dataone.daks.provexdb.DAO.models.dao.ProvenanceStageDao;
import org.dataone.daks.provexdb.DAO.models.dto.ProvenanceStage;


/**
 * This is the DAO imlementation class.
 *
 * @author generated
 */
public class ProvenanceStageDaoImpl extends AbstractDaoImpl<ProvenanceStage> implements ProvenanceStageDao {

    private static final String TABLE_NAME = "provenance_stage";

    protected static final String SELECT_COLUMNS = "traceId, reqId, stageId, startNodeId, endNodeId, edgeLabel";

    private static final String SQL_INSERT = "INSERT INTO provenance_stage (traceId,reqId,stageId,startNodeId,endNodeId,edgeLabel) VALUES (?,?,?,?,?,?)";

    public ProvenanceStageDaoImpl( Connection conn ) {
        super( conn );
    }

    /**
     * Finds records.
     */
    public ProvenanceStage[] findByTraceRequestStage( String traceId, String reqId, String stageId ) {
        return findManyArray( "traceId=? and reqId=? and stageId=? ", 0, -1, traceId, reqId, stageId);
    }

    /**
     * Inserts a new record.
     */
    public void insert( ProvenanceStage dto ) throws DaoException {
        PreparedStatement stmt = null;

        debugSql( SQL_INSERT, dto );

        try {
            stmt = conn.prepareStatement( SQL_INSERT );

            if ( dto.getTraceId() == null ) {
                throw new DaoException("Value of column 'traceId' cannot be null");
            }
            checkMaxLength( "traceId", dto.getTraceId(), 32 );
            stmt.setString( 1, dto.getTraceId() );

            if ( dto.getReqId() == null ) {
                throw new DaoException("Value of column 'reqId' cannot be null");
            }
            checkMaxLength( "reqId", dto.getReqId(), 32 );
            stmt.setString( 2, dto.getReqId() );

            if ( dto.getStageId() == null ) {
                throw new DaoException("Value of column 'stageId' cannot be null");
            }
            checkMaxLength( "stageId", dto.getStageId(), 32 );
            stmt.setString( 3, dto.getStageId() );

            if ( dto.getStartNodeId() == null ) {
                throw new DaoException("Value of column 'startNodeId' cannot be null");
            }
            checkMaxLength( "startNodeId", dto.getStartNodeId(), 32 );
            stmt.setString( 4, dto.getStartNodeId() );

            if ( dto.getEndNodeId() != null ) {
                checkMaxLength( "endNodeId", dto.getEndNodeId(), 32 );
            }
            stmt.setString( 5, dto.getEndNodeId() );

            if ( dto.getEdgeLabel() == null ) {
                throw new DaoException("Value of column 'edgeLabel' cannot be null");
            }
            checkMaxLength( "edgeLabel", dto.getEdgeLabel(), 32 );
            stmt.setString( 6, dto.getEdgeLabel() );

            int n = stmt.executeUpdate();
        }
        catch (SQLException e) {
            errorSql( e, SQL_INSERT, dto );
            handleException( e );
            throw new DBException( e );
        }
        finally {
            if (stmt != null) try { stmt.close(); } catch (SQLException e) {}
        }
    }

    /**
     * Returns the table name.
     */
    public String getTableName() {
        return TABLE_NAME;
    }

    protected String getSelectColumns() {
        return SELECT_COLUMNS;
    }

    protected ProvenanceStage fetch( ResultSet rs ) throws SQLException {
        ProvenanceStage dto = new ProvenanceStage();
        dto.setTraceId( rs.getString( 1 ));
        dto.setReqId( rs.getString( 2 ));
        dto.setStageId( rs.getString( 3 ));
        dto.setStartNodeId( rs.getString( 4 ));
        dto.setEndNodeId( rs.getString( 5 ));
        dto.setEdgeLabel( rs.getString( 6 ));

        return dto;
    }

    protected ProvenanceStage[] toArray(ArrayList<ProvenanceStage> list ) {
        ProvenanceStage[] ret = new ProvenanceStage[ list.size() ];
        return list.toArray( ret );
    }

}
