/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package org.dataone.daks.provexdb.DAO.models.dao;

import java.sql.Connection;


/**
 * This is the main class for obtaining DAO objects.
 * It looks for the system property called "DAO.models.dao.DB_TYPE"
 * and its value is used as the DAO implementation subpackage name.
 * The default value is "mysql".
 * The name of the Factory class is assumed to be "DaoFactoryImpl"
 * and it must have the default constructor defined.
 *
 * @author generated
 */
public class DaoFactory {

    private static Factory factory;

    static {
        String pkgDao = DaoFactory.class.getPackage().getName();
        String pkgImpl = pkgDao + '.' + System.getProperty( pkgDao + ".DB_TYPE", "mysql" );
        try {
            Class<?> aclazz = Class.forName( pkgImpl + ".DaoFactoryImpl" );
            Class<? extends Factory> clazz = aclazz.asSubclass( Factory.class );
            factory = clazz.newInstance();
        }
        catch (Exception e) {
            throw new Error("A problem occurred when resolving DAO factory class", e);
        }
    }


    ////////////////////////////////////////////////////////////////////////////
    // Static methods
    ////////////////////////////////////////////////////////////////////////////

    public static EdgeDao createEdgeDao( Connection conn ) {
        return factory.createEdgeDao( conn );
    }

    public static PolicyViolationDao createPolicyViolationDao( Connection conn ) {
        return factory.createPolicyViolationDao( conn );
    }

    public static ProvenanceStageDao createProvenanceStageDao( Connection conn ) {
        return factory.createProvenanceStageDao( conn );
    }

    public static TcDao createTcDao( Connection conn ) {
        return factory.createTcDao( conn );
    }

    public static TcTempDao createTcTempDao( Connection conn ) {
        return factory.createTcTempDao( conn );
    }

    public static UserRequestDetailDao createUserRequestDetailDao( Connection conn ) {
        return factory.createUserRequestDetailDao( conn );
    }

    public static DataDao createDataDao( Connection conn ) {
        return factory.createDataDao( conn );
    }

    public static ActorDao createActorDao( Connection conn ) {
        return factory.createActorDao( conn );
    }

    public static UserRequestMasterDao createUserRequestMasterDao( Connection conn ) {
        return factory.createUserRequestMasterDao( conn );
    }


    ////////////////////////////////////////////////////////////////////////////
    // Inner classes
    ////////////////////////////////////////////////////////////////////////////

    public static abstract class Factory {

        public abstract EdgeDao createEdgeDao( Connection conn );

        public abstract PolicyViolationDao createPolicyViolationDao( Connection conn );

        public abstract ProvenanceStageDao createProvenanceStageDao( Connection conn );

        public abstract TcDao createTcDao( Connection conn );

        public abstract TcTempDao createTcTempDao( Connection conn );

        public abstract UserRequestDetailDao createUserRequestDetailDao( Connection conn );

        public abstract DataDao createDataDao( Connection conn );

        public abstract ActorDao createActorDao( Connection conn );

        public abstract UserRequestMasterDao createUserRequestMasterDao( Connection conn );

    }
}
