package propub;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ExternalResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

public class Gui extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Panel panel_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private TabSheet tabsheet;
	@AutoGenerated
	private OptionGroup optionGroup_1;
	@AutoGenerated
	private Button button_8;
	@AutoGenerated
	private Button button_7;
	@AutoGenerated
	private Button button_6;
	@AutoGenerated
	private Button button_5;
	@AutoGenerated
	private Button button_4;
	@AutoGenerated
	private Button button_3;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private Button button1;
	@AutoGenerated
	private Embedded embedded_3;
	@AutoGenerated
	private Label label_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Gui() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label_1
		label_1 = new Label();
		label_1.setCaption("ProPub");
		label_1.setImmediate(false);
		label_1.setWidth("180px");
		label_1.setHeight("38px");
		label_1.setValue("<center><h2>ProPub</h2></center>");
		label_1.setContentMode(3);
		mainLayout.addComponent(label_1, "top:2.0px;left:20.0px;");
		
		// embedded_3
		embedded_3 = new Embedded();
		embedded_3.setImmediate(false);
		embedded_3.setWidth("50px");
		embedded_3.setHeight("50px");
		embedded_3.setSource(new ExternalResource(
				"http://www.californiasailplanes.com/duckedit.jpg"));
		embedded_3.setType(1);
		embedded_3.setMimeType("image/png");
		mainLayout.addComponent(embedded_3, "top:2.0px;left:200.0px;");
		
		// button1
		button1 = new Button();
		button1.setCaption("Login");
		button1.setImmediate(false);
		button1.setWidth("-1px");
		button1.setHeight("-1px");
		mainLayout.addComponent(button1, "top:16.0px;left:555.0px;");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Open");
		button_1.setImmediate(false);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1, "top:54.0px;left:16.0px;");
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("Save");
		button_2.setImmediate(false);
		button_2.setWidth("-1px");
		button_2.setHeight("-1px");
		mainLayout.addComponent(button_2, "top:54.0px;left:99.0px;");
		
		// button_3
		button_3 = new Button();
		button_3.setCaption("SL");
		button_3.setImmediate(false);
		button_3.setWidth("-1px");
		button_3.setHeight("-1px");
		mainLayout.addComponent(button_3, "top:54.0px;left:200.0px;");
		
		// button_4
		button_4 = new Button();
		button_4.setCaption("NI");
		button_4.setImmediate(false);
		button_4.setWidth("-1px");
		button_4.setHeight("-1px");
		mainLayout.addComponent(button_4, "top:54.0px;left:250.0px;");
		
		// button_5
		button_5 = new Button();
		button_5.setCaption("<<");
		button_5.setImmediate(false);
		button_5.setWidth("-1px");
		button_5.setHeight("-1px");
		mainLayout.addComponent(button_5, "top:54.0px;left:320.0px;");
		
		// button_6
		button_6 = new Button();
		button_6.setCaption("<");
		button_6.setImmediate(false);
		button_6.setWidth("-1px");
		button_6.setHeight("-1px");
		mainLayout.addComponent(button_6, "top:54.0px;left:368.0px;");
		
		// button_7
		button_7 = new Button();
		button_7.setCaption(">");
		button_7.setImmediate(false);
		button_7.setWidth("-1px");
		button_7.setHeight("-1px");
		mainLayout.addComponent(button_7, "top:54.0px;left:407.0px;");
		
		// button_8
		button_8 = new Button();
		button_8.setCaption(">>");
		button_8.setImmediate(false);
		button_8.setWidth("-1px");
		button_8.setHeight("-1px");
		mainLayout.addComponent(button_8, "top:54.0px;left:446.0px;");
		
		// optionGroup_1
		optionGroup_1 = new OptionGroup();
		optionGroup_1.setImmediate(false);
//		optionGroup_1.addStyleName("horizontal");
		optionGroup_1.setWidth("102px");
		optionGroup_1.setHeight("100.0%");
		mainLayout.addComponent(optionGroup_1,
				"top:52.0px;bottom:457.0px;left:520.0px;");
		
		// tabsheet
		tabsheet = new TabSheet();
		tabsheet.setImmediate(false);
		tabsheet.setWidth("264px");
		tabsheet.setHeight("380px");
		mainLayout.addComponent(tabsheet, "top:140.0px;left:16.0px;");
		
		// panel_2
		panel_2 = buildPanel_2();
		mainLayout.addComponent(panel_2, "top:147.0px;left:280.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_2() {
		// common part: create layout
		panel_2 = new Panel();
		panel_2.setImmediate(false);
		panel_2.setWidth("340px");
		panel_2.setHeight("373px");
		
		// verticalLayout_3
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("136.69%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(false);
		panel_2.setContent(verticalLayout_3);
		
		return panel_2;
	}

}
